### ISSUE TITLE
Need to add a .gitignore 

### ISSUE THREAD

**Issue by meetagrawal09** [shubham7668/hacktober#105]
I see some directories having **_.exe_** files committed. A gitignore can help to maintain the repository better by not committing unwanted files

**Comment by meetagrawal09** [comment]
@shubham7668, can you please confirm this issue

**Comment by shubham7668** [comment]
Done @meetagrawal09 
Lets contribute
Make sure to follow all rules for hacktoberfest-accepted tag

**Comment by meetagrawal09** [comment]
@shubham7668, I have raised a PR #110
