### ISSUE TITLE
Error in a Link tag of website.html

### ISSUE THREAD

**Issue by KryptonANSHU** [shubham7668/hacktober#135]
Hey, I looked at the last project of the repo that is website.html. I noticed a Error that a link tag is giving.
it is not redirecting the user to second file. (Because there is no 2nd Page)

I would like to fix this issue by creating a 2nd Page 

![Screenshot 2022-10-02 115629](https://user-images.githubusercontent.com/72062616/193441122-1bced159-d099-4367-aeda-dad3b0a49177.png)

Error Page
![image](https://user-images.githubusercontent.com/72062616/193441146-6541649f-75c0-4059-aca1-31292aeff9b7.png)

**Comment by lognoroy** [comment]
hey @KryptonANSHU  I can fix this. Pls assign me.

**Comment by KryptonANSHU** [comment]
Brother, I have found the issue and I also want to fix this
Hey @shubham7668 can you assign this to me

**Comment by shubham7668** [comment]
Lets go @KryptonANSHU

**Comment by KryptonANSHU** [comment]
@shubham7668 
Corrected it and sent the PR
Kindly review and Accept :)
