### ISSUE TITLE
basic timer/stopwatch using js

### ISSUE THREAD

**Issue by sidhrth04** [shubham7668/hacktober#144]
@shubham7668 , i would like to add a basic timer/stopwatch using js placed on animated profile cards using html and css
please assign me this issue under hacktober fest 
it will be a great help.

**Comment by shubham7668** [comment]
done @sidhrth04

**Comment by invad3r07** [comment]
Ping me after pr @sidhrth04 
will close this issue

**Comment by sidhrth04** [comment]
i created a pr @INVAD3R
you can close the issue
