### ISSUE TITLE
Repository Excluded from Hacktoberfest

### ISSUE THREAD

**Issue by meetagrawal09** [shubham7668/hacktober#231]
<img width="878" alt="image" src="https://user-images.githubusercontent.com/73902874/194050076-9fead394-6c1f-4bd5-bb21-c50d7837efc5.png">

**Comment by meetagrawal09** [comment]
@shubham7668, this repo has been excluded from hacktoberfest

**Comment by shubham7668** [comment]
Thanks for updating
