### ISSUE TITLE
2sum

### ISSUE THREAD

**Issue by shubham7668** [shubham7668/hacktober#28]
Given an array of integers nums and an integer target, return indices of the two numbers such that they add up to target.

**Comment by sarthak17jain** [comment]
Please assign me this issue.

**Comment by sayanm16** [comment]
Hey @shubham7668 assign to me

**Comment by AJTEACH** [comment]
Hey @shubham7668 please assign this issue to me

**Comment by saurabh9887** [comment]
please assign it to me

**Comment by GeniusNirmit** [comment]
Please assign this to me
