### ISSUE TITLE
Longest Palindromic Substring

### ISSUE THREAD

**Issue by shubham7668** [shubham7668/hacktober#31]
Given a string s, return the longest palindromic substring in s.

A string is called a palindrome string if the reverse of that string is the same as the original string.

**Comment by kalpitshah2311** [comment]
I am interested to be assigned to this issue.
It would help me to learn and contribute 😄

**Comment by shubham7668** [comment]
sure

**Comment by kalpitshah2311** [comment]
should I modify the same file added by amajaying ?
