### ISSUE TITLE
Reverse Integer

### ISSUE THREAD

**Issue by shubham7668** [shubham7668/hacktober#32]
Reverse a integer

**Comment by aatharvauti** [comment]
Can I get more details about the problem mentioned?

**Comment by sayanm16** [comment]
Hey @shubham7668 assign this to me

**Comment by rohit07v** [comment]
hey @shubham7668 assign this to me pls . i can do it in short trick in python

**Comment by shubhammaurya767** [comment]
> Reverse a integer

Hey @shubham7668 Can u assign this to me. I will add cpp code for this.

**Comment by saurabh9887** [comment]
hey please assign me this issue. I will address this issue using cpp
