### ISSUE TITLE
Palindrome number

### ISSUE THREAD

**Issue by shubham7668** [shubham7668/hacktober#33]
Given an integer x, return true if x is palindrome integer.

An integer is a palindrome when it reads the same backward as forward.

For example, 121 is a palindrome while 123 is not.

**Comment by shivenducs1136** [comment]
Hi, Can you please Assign this issue to me.

**Comment by shubham7668** [comment]
done

**Comment by MokshadVaidya** [comment]
hey can you assign it to me

**Comment by ridhika123269** [comment]
hey! can you please assign me this. I will do it in cpp

**Comment by saurabh9887** [comment]
Please assign me, this is my first contribution to open source and currently, I am doing competitive programming in c++ only so I can do it more easily.
