### ISSUE TITLE
Create a webpage using html & css

### ISSUE THREAD

**Issue by shubham7668** [shubham7668/hacktober#56]
Star the repo 
Ask for assign for faster merging

**Comment by soumdatta81** [comment]
assign this to me

**Comment by AmanSingh81757** [comment]
Please assign to me

**Comment by muneeb-i-khan** [comment]
Assign it to me @shubham7668

**Comment by Mahekjain2706** [comment]
Hey ,can you assign it to me @shubham7668 and tagged as a hacktoberfest label :)
