### ISSUE TITLE
Write any DSA problem on a html page

### ISSUE THREAD

**Issue by shubham7668** [shubham7668/hacktober#57]
Star the repo
Ask for assign for faster merge

**Comment by muneeb-i-khan** [comment]
Assign it to me

**Comment by muneeb-i-khan** [comment]
Should the page be styled as well?

**Comment by sayanm16** [comment]
Hey @shubham7668 assign this to me

**Comment by shubham7668** [comment]
done

**Comment by muneeb-i-khan** [comment]
I am done with this
Already made a PR
