### ISSUE TITLE
Create basic portfolio using html

### ISSUE THREAD

**Issue by shubham7668** [shubham7668/hacktober#84]
Rules:-
1)Follow me and add star in this repository
2)No c++/c file will be accepted
3)Comment for assign this task to you

Follow all rules you will get hacktoberfest-accepted tag

**Comment by ansharora28** [comment]
Hi! Please assign this issue to me

**Comment by shubham7668** [comment]
Done @ansharora28

**Comment by vinitfreakk** [comment]
would like to contribute in this

**Comment by shubham7668** [comment]
Good to go @vinitfreakk 
Make sure to follow all rules for hacktoberfest-accepted tag
Do not forget to add snapshot of working website

**Comment by Atharva-D** [comment]
I would love to contribute to this issue. Please assign me @shubham7668

**Comment by shubham7668** [comment]
Lets go @Atharva-D

**Comment by Atharva-D** [comment]
I have made a pull request , kindly review it and merge it @shubham7668
