### ISSUE TITLE
create basic portfolio using html & css

### ISSUE THREAD

**Issue by shubham7668** [shubham7668/hacktober#85]
Rules:-
1)Follow me and add star in this repository
2)No c++/c file will be accepted
3)Comment for assign this task to you

Follow all rules you will get hacktoberfest-accepted tag

**Comment by Skysparko** [comment]
can you please assign this task to me

**Comment by rising-star2712** [comment]
hi @shubham7668 could i work on the following issue ?

**Comment by vinitfreakk** [comment]
can I work on this issue. at least I will have portfolio site with me 😁😁

**Comment by shubham7668** [comment]
Done @Skysparko @rising-star2712 @vinitfreakk 
Lets contibute
Follow all rules for hacktoberfest-accepted tag
