### ISSUE TITLE
create portfolio using html,css & javacript

### ISSUE THREAD

**Issue by shubham7668** [shubham7668/hacktober#86]
Rules:-
1)Follow me and add star in this repository
2)No c++/c file will be accepted
3)Comment for assign this task to you

Follow all rules you will get hacktoberfest-accepted tag

**Comment by sachin2709** [comment]
I want to work on this task,please assign it to me @shubham7668

**Comment by shubham7668** [comment]
done

**Comment by shubham7668** [comment]
@sachin2709

**Comment by sachin2709** [comment]
For whom I need to  make portfolio sir @shubham7668  ??

**Comment by shubham7668** [comment]
You can make for yourself ☺️
Add those files and snapshots
I will merge if it will following all rules

**Comment by ShivanshDengla** [comment]
Hey, can i work for this issue?

**Comment by dheerajgajula02** [comment]
can I work on this ? @shubham7668 
thank you

**Comment by Ishika-jain** [comment]
Can I get assigned for this?

**Comment by heisdinesh** [comment]
Hey @shubham7668 can i work on this issue ?

**Comment by shubham7668** [comment]
Done @ShivanshDengla @Ishika-jain @heisdinesh @dheerajgajula02 
Lets contribute
Make sure to follow all rules for hacktoberfest-accepted tag
Do add snapshots of working portfolio

**Comment by dhairyaostwal** [comment]
@shubham7668 can I refactor and structure the repository to create a separate space for Web Dev projects

**Comment by lognoroy** [comment]
I want to work on this task,please assign it to me @shubham7668

**Comment by shubham7668** [comment]
Done @dhairyaostwal @lognoroy 
Make sure to follow rules

**Comment by vishalpatil20** [comment]
Hey @shubham7668 can I work on this task??
Can you assign me this

**Comment by shubham7668** [comment]
Lets go @vishalpatil20

**Comment by shubham7668** [comment]
Closing this issue now 
Requirement fullfiled

**Comment by invad3r07** [comment]
Closing issue @shubham7668 
Enough assignees
