### ISSUE TITLE
Median of Two Sorted Arrays in python(only)

### ISSUE THREAD

**Issue by shubham7668** [shubham7668/hacktober#87]
Rules:-
1)Follow me and add star in this repository
2)No c++/c file will be accepted
3)Comment for assign this task to you

Follow all rules you will get hacktoberfest-accepted tag

**Comment by Anway-Agte** [comment]
Can I work on this ?

**Comment by bhushan162** [comment]
@shubham7668 can I work on this?

**Comment by RushikeshMali05** [comment]
Hi @shubham7668, can i please work on this?

**Comment by shubham7668** [comment]
Done @Anway-Agte @bhushan162 @RushikeshMali05 
Lets contribute
Make sure to follow all rules for hacktoberfest-accepted tag

**Comment by RushikeshMali05** [comment]
Hi @shubham7668 , I have completed the assigned task. I had already made a PR before you assigned me the task. I have made another PR for the assigned task. Please review and merge it. Thanks!
