### ISSUE TITLE
Longest Substring Without Repeating Characters in python

### ISSUE THREAD

**Issue by shubham7668** [shubham7668/hacktober#89]
Rules:-
1)Follow me and add star in this repository
2)No c++/c file will be accepted
3)Comment for assign this task to you

Follow all rules you will get hacktoberfest-accepted tag

**Comment by Ansfred** [comment]
Would love to work on this problem.

**Comment by RushikeshMali05** [comment]
can i please work on this problem?

**Comment by lognoroy** [comment]
Sir I want to work pls give me a chance.

**Comment by RushikeshMali05** [comment]
I have created a PR for the assigned issue. Kindly review and merge it.
