### ISSUE TITLE
Set Matrix Zeroes in python

### ISSUE THREAD

**Issue by shubham7668** [shubham7668/hacktober#90]
Rules:-
1)Follow me and add star in this repository
2)No c++/c file will be accepted
3)Comment for assign this task to you

Follow all rules you will get hacktoberfest-accepted tag

**Comment by dheerajgajula02** [comment]
hi @shubham7668  can i work on this issue?

**Comment by RushikeshMali05** [comment]
Hi, can I please work on this issue?

**Comment by lognoroy** [comment]
Hello sir, I followed you already and added star also. I will write code in java. Please give a chance @shubham7668 .
