### ISSUE TITLE
Linked List Cycle in python

### ISSUE THREAD

**Issue by shubham7668** [shubham7668/hacktober#91]
Rules:-
1)Follow me and add star in this repository
2)No c++/c file will be accepted
3)Comment for assign this task to you

Follow all rules you will get hacktoberfest-accepted tag

**Comment by ShivanshDengla** [comment]
Hey,
Can i write the code for this issue?

**Comment by ShivanshDengla** [comment]
Hey,
I added the issue for this code #103 Please tell me if theres a mistake, ill correct it,
Thanks
