### ISSUE TITLE
Happy Number in python

### ISSUE THREAD

**Issue by shubham7668** [shubham7668/hacktober#92]
Rules:-
1)Follow me and add star in this repository
2)No c++/c file will be accepted
3)Comment for assign this task to you

Follow all rules you will get hacktoberfest-accepted tag

**Comment by ashutosh7i** [comment]
can i do this task?

**Comment by ashutosh7i** [comment]
please assign it to me

**Comment by rising-star2712** [comment]
Hi could I work on the following issue ?

**Comment by dheerajgajula02** [comment]
hi @shubham7668  can I work on this issue

**Comment by ShivanshDengla** [comment]
hey,
can i work on this issue?

**Comment by shubham7668** [comment]
Done @ShivanshDengla 
Lets contribute
Make sure to follow all rules for hacktoberfest-accepted tag
