### ISSUE TITLE
Implement Trie (Prefix Tree) in python

### ISSUE THREAD

**Issue by shubham7668** [shubham7668/hacktober#93]
Rules:-
1)Follow me and add star in this repository
2)No c++/c file will be accepted
3)Comment for assign this task to you

Follow all rules you will get hacktoberfest-accepted tag

**Comment by shivenducs1136** [comment]
hey can you assign this issue to me?

**Comment by shivenducs1136** [comment]
![image](https://user-images.githubusercontent.com/77795429/193422636-f6d41bcb-d5cc-4265-9be1-b2f0c2db5082.png)

Hi I have implemented trie, Please merge my PR
