### ISSUE TITLE
Maximum Subarray in python

### ISSUE THREAD

**Issue by shubham7668** [shubham7668/hacktober#95]
Rules:-
1)Follow me and add star in this repository
2)No c++/c file will be accepted
3)Comment for assign this task to you

Follow all rules you will get hacktoberfest-accepted tag

**Comment by yogitha02** [comment]
@shubham7668 Please do assign me, i would be glad to finish this task in python with time complexity and auxiliary space

**Comment by shubham7668** [comment]
Sure @yogitha02

**Comment by Ishika-jain** [comment]
can you assign this to me for js

**Comment by shubham7668** [comment]
Sure @Ishika-jain 
Make sure to follow all rules
