### ISSUE TITLE
Edit Distance in python

### ISSUE THREAD

**Issue by shubham7668** [shubham7668/hacktober#96]
Rules:-
1)Follow me and add star in this repository
2)No c++/c file will be accepted
3)Comment for assign this task to you

Follow all rules you will get hacktoberfest-accepted tag

**Comment by rising-star2712** [comment]
Hi could I work on the following issue

**Comment by rising-star2712** [comment]
@shubham7668 could I work on the following issue ?

**Comment by shubham7668** [comment]
Done @rising-star2712 
Lets contribute
Make sure to follow all rules for hacktoberfest-accepted tag
